const { chromium } = require('playwright');
(async()=>{ const b=await chromium.launch(); const errs=[];
  const p=await b.newPage({viewport:{width:1300,height:800}}); p.on('pageerror',e=>errs.push(e.message));
  await p.goto('http://localhost:8765/index.html'); await p.waitForTimeout(600);
  await p.evaluate(()=>{ try{localStorage.clear();}catch(e){} TO.newGame(); TO.S.fuel=80; TO.S.credits=1e6; TO.geaendert(); TO.ANIM.fast=true; });
  await p.evaluate(()=>{ TO.openRoute({node:'moon.surf',site:'shackleton'}); TO.startAutopilot(); TO.ANIM.fast=true; });
  await p.waitForFunction(()=>!TO.S.ui.auto&&!TO.S.busy,{timeout:90000}); await p.waitForTimeout(400);
  console.log(await p.evaluate(()=>({node:TO.S.node,site:TO.S.site,view:TO.S.ui.view,mainHidden:document.getElementById('mainview').hidden,msg:TO.S.msg})));
  await p.screenshot({path:'land2.png'});
  console.log('Fehler',errs); await b.close(); })();
