const { chromium } = require('playwright');
(async()=>{ const b=await chromium.launch(); const errs=[];
  const p=await b.newPage({viewport:{width:1300,height:800}}); p.on('pageerror',e=>errs.push(e.message));
  await p.goto('http://localhost:8765/dist/index.html'); await p.waitForTimeout(600);
  await p.evaluate(()=>{ try{localStorage.clear();}catch(e){} TO.newGame(); TO.S.domain.fuel=80; TO.S.domain.credits=1e6; TO.changed(); TO.ANIM.fast=true; });
  await p.evaluate(()=>{ TO.openRoute({node:'moon.surf',site:'shackleton'}); TO.launchAutopilot(); TO.ANIM.fast=true; });
  await p.waitForFunction(()=>!TO.S.action.auto&&!TO.S.action.busy,{timeout:90000}); await p.waitForTimeout(400);
  console.log(await p.evaluate(()=>({node:TO.S.domain.node,site:TO.S.domain.site,view:TO.UI.view,mainHidden:document.getElementById('mainview').hidden,msg:TO.UI.msg})));
  await p.screenshot({path:'land2.png'});
  console.log('Errors',errs); await b.close(); })();
