// Writes js/game/transfertables.ts: the transfer table of every pair of planets, computed from their
// orbits with the solver in game/physics. Run it (npm run tables) after changing an orbit or the
// grid in game/world.ts; tests/unit.js fails as long as the tables and the orbits disagree.
//
// Usage:  node tools/transfertables.js
const { execFileSync } = require('node:child_process');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { pathToFileURL } = require('node:url');

// game/physics reaches basics.js, which asks the browser whether to reduce motion
globalThis.matchMedia = () => ({ matches: false });

(async () => {
  const root = path.join(__dirname, '..'), out = fs.mkdtempSync(path.join(os.tmpdir(), 'transferorbit-tables-'));
  // Only world and physics are needed: a type error elsewhere does not stop the tables
  try { execFileSync(path.join(root, 'node_modules', '.bin', 'tsc'), ['-p', path.join(root, 'tsconfig.json'), '--noEmit', 'false', '--rootDir', root, '--outDir', out], { stdio: 'inherit' }); }
  catch (e) { if (!fs.existsSync(path.join(out, 'js', 'game', 'physics.js'))) throw e; console.log('(type errors above; the tables only need game/world and game/physics)'); }
  fs.writeFileSync(path.join(out, 'package.json'), '{"type":"module"}');
  const load = m => import(pathToFileURL(path.join(out, 'js', m + '.js')).href);
  const [world, physics] = await Promise.all([load('game/world'), load('game/physics')]);
  const { PLANETS, TABLE_GRID, vInfToByte } = world, t0 = Date.now();
  const rows = [];
  for (const a of PLANETS) for (const b of PLANETS) {
    if (a === b) continue;
    const t = physics.computeTable(a, b), n = t.vInfDep.length, bytes = Buffer.alloc(2 * n);
    for (let k = 0; k < n; k++) { bytes[k] = vInfToByte(t.vInfDep[k]); bytes[n + k] = vInfToByte(t.vInfArr[k]); }
    rows.push(`  '${a}>${b}':[${+t.flightRange[0].toFixed(6)},${+t.flightRange[1].toFixed(6)},'${bytes.toString('base64')}'],`);
  }
  const text = `// Generated by tools/transfertables.js from the orbits in game/world.ts: do not edit by hand.
// For every pair of planets: the shortest and longest flight (days), then base64 of one byte per
// cell, first the excess speeds at departure, then those at arrival (world.byteToVInf).
export const TRANSFER_GRID = {angleSteps:${TABLE_GRID.angleSteps}, flightSteps:${TABLE_GRID.flightSteps}} as const;
export const TRANSFER_DATA: Readonly<Record<string, readonly [number, number, string]>> = {
${rows.join('\n')}
};
`;
  fs.writeFileSync(path.join(root, 'js', 'game', 'transfertables.ts'), text);
  fs.rmSync(out, { recursive: true, force: true });
  console.log(`${rows.length} tables written in ${((Date.now() - t0) / 1000).toFixed(1)} s, ${(text.length / 1024).toFixed(0)} KiB`);
})();
